# Makefile for the hackster
# ==============================================================================
# Configuration area:
# ==============================================================================

# List of source files
SYNTH_SOURCES = spi_les_top.v \
				les_top.v \
				shift_register.v \
				aes/aes_sbox_lut.v \
				aes/aes_sbox.v 

PCF_SOURCE = spi_les.pcf

# Top-level module
SYNTH_TOP_MODULE = spi_les_top

include ../hackster.mk