# ==============================================================================
# Project configuration
# ==============================================================================

# List of source files
SYNTH_SOURCES = spi_simple_top.v shift_register.v

SIM_SOURCES = $(SYNTH_SOURCES) 
PCF_SOURCE = spi_simple.pcf

# Top-level module
SYNTH_TOP_MODULE = spi_simple_top
SIM_TOP_MODULE = 

include ../hackster.mk
