# ==============================================================================
# Project configuration
# ==============================================================================

# List of source files
SYNTH_SOURCES = simple_spi_top.v scan_register.v

SIM_SOURCES = $(SYNTH_SOURCES) 
PCF_SOURCE = simple_spi.pcf

# Top-level module
SYNTH_TOP_MODULE = simple_spi_top
SIM_TOP_MODULE = simple_spi_top

include ../hackster.mk
