# ==============================================================================
# Configuration area:
# ==============================================================================

# List of source files
SYNTH_SOURCES = power_chain.v
SIM_SOURCES = power_chain_tb.v $(SYNTH_SOURCES)
PCF_SOURCE = power_chain.pcf

# Top-level module
SYNTH_TOP_MODULE = power_chain
SIM_TOP_MODULE = power_chain_tb

include ../hackster.mk