# ==============================================================================
# Configuration area:
# ==============================================================================


######### Builds for Step 4 ############
SYNTH_SOURCES = i2c_trojan_rtc.v i2c_master.v i2c_simple_slave.v i2c_pin_primitives_ice40.v
PCF_SOURCE = i2c_trojan.pcf
SYNTH_TOP_MODULE = i2c_trojan_rtc

include ../hackster.mk