# ==============================================================================
# Configuration area:
# ==============================================================================

# List of source files
SYNTH_SOURCES = i2c_write_eeprom.v i2c_master.v i2c_pin_primitives_ice40.v
PCF_SOURCE = i2c_registers.pcf

# Top-level module
SYNTH_TOP_MODULE = i2c_write_eeprom
SIM_TOP_MODULE = i2c_master_tb


include ../hackster.mk