# ==============================================================================
# Configuration area:
# ==============================================================================

# List of source files
SYNTH_SOURCES = i2c_registers_top.v i2c_simple_slave.v i2c_pin_primitives_ice40.v
SIM_SOURCES = i2c_simple_slave_tb.v i2c_simple_slave.v
PCF_SOURCE = i2c_registers.pcf

# Top-level module
SYNTH_TOP_MODULE = i2c_registers_top
SIM_TOP_MODULE = i2c_simple_slave_tb

include ../hackster.mk