# ==============================================================================
# Configuration area:
# ==============================================================================

# List of source files
SYNTH_SOURCES = top.v
SIM_SOURCES = $(SYNTH_SOURCES)
PCF_SOURCE = top.pcf

# Top-level module
SYNTH_TOP_MODULE = top
SIM_TOP_MODULE = top

include ../../examples/hackster.mk