# ==============================================================================
# Configuration area:
# ==============================================================================

# List of source files
SYNTH_SOURCES = i2c_passthrough.v
SIM_SOURCES = 
PCF_SOURCE = i2c_passthrough.pcf

# Top-level module
SYNTH_TOP_MODULE = i2c_passthrough
SIM_TOP_MODULE = 

include ../hackster.mk