# ==============================================================================
# Project configuration
# ==============================================================================

# List of source files
SYNTH_SOURCES = puf.v
SIM_SOURCES = $(SYNTH_SOURCES)
PCF_SOURCE = puf.pcf

# Top-level module
SYNTH_TOP_MODULE = puf
SIM_TOP_MODULE = puf

include ../hackster.mk
