# ==============================================================================
# Project configuration
# ==============================================================================

# List of source files
SYNTH_SOURCES = rgb_demo.v
SIM_SOURCES = rgb_demo_tb.v $(SYNTH_SOURCES)
PCF_SOURCE = rgb_demo.pcf

# Top-level module
SYNTH_TOP_MODULE = rgb_demo
SIM_TOP_MODULE = rgb_demo_tb

include ../hackster.mk
