# ==============================================================================
# Project configuration
# ==============================================================================

# List of source files
SYNTH_SOURCES = ring_oscillator.v
SIM_SOURCES = $(SYNTH_SOURCES)
PCF_SOURCE = ring_oscillator.pcf

# Top-level module
SYNTH_TOP_MODULE = ring_oscillator
SIM_TOP_MODULE = ring_oscillator

include ../hackster.mk
